import type {
  User, ProProfile, BuyerProfile, Brief, Proposal, Contract,
  PaymentEvidence, Payout, Refund, Dispute, Review, SupportTicket,
  NotificationItem, AuditEvent, KycSubmission, GigDraft, OfflineInstrument,
  TrustSafetyCase, Milestone,
} from "./types";

export const SEED_USERS: User[] = [
  { id: "BUY-1042", role: "buyer", name: "Northstar Labs", email: "ops@northstarlabs.example", headline: "B2B SaaS company", avatarColor: "#0F766E", location: "Kochi, India", industry: "B2B SaaS", verification: "Account ready", verificationStatus: "approved" },
  { id: "PRO-2088", role: "pro", name: "Akhil Menon", email: "akhil@example.com", headline: "Product Designer and UX Researcher", avatarColor: "#7C3AED", location: "Bengaluru, India", industry: "Design", verification: "Identity reviewed", verificationStatus: "approved" },
  { id: "PRO-2099", role: "pro", name: "Priya Nair", email: "priya@example.com", headline: "Frontend Engineer (React/Next.js)", avatarColor: "#0891B2", location: "Kochi, India", industry: "Engineering", verification: "Identity reviewed", verificationStatus: "approved" },
  { id: "PRO-2101", role: "pro", name: "Rahul Verma", email: "rahul@example.com", headline: "Brand & Identity Designer", avatarColor: "#DB2777", location: "Mumbai, India", industry: "Design", verification: "Identity reviewed", verificationStatus: "approved" },
  { id: "PRO-2102", role: "pro", name: "Sara Khan", email: "sara@example.com", headline: "UX Researcher", avatarColor: "#CA8A04", location: "Pune, India", industry: "Research", verification: "Pending review", verificationStatus: "under_review" },
  { id: "BUY-1050", role: "buyer", name: "Verdant Retail", email: "finance@verdant.example", headline: "Omnichannel retail", avatarColor: "#15803D", location: "Bengaluru, India", industry: "Retail", verification: "Account ready", verificationStatus: "approved" },
  { id: "ADM-S01", role: "admin_support", name: "Meera S (Support T1)", email: "meera@quickquid.example", avatarColor: "#475569", verification: "Staff", verificationStatus: "approved" },
  { id: "FIN-F01", role: "finance", name: "Arjun K (Finance T2)", email: "arjun@quickquid.example", avatarColor: "#1E40AF", verification: "Staff", verificationStatus: "approved" },
  { id: "RSK-R01", role: "risk", name: "Deepa R (Risk T3)", email: "deepa@quickquid.example", avatarColor: "#9F1239", verification: "Staff", verificationStatus: "approved" },
  { id: "OPS-O01", role: "ops_manager", name: "Vikram T (Ops Manager)", email: "vikram@quickquid.example", avatarColor: "#334155", verification: "Staff", verificationStatus: "approved" },
];

export const SEED_PRO_PROFILES: ProProfile[] = [
  {
    userId: "PRO-2088",
    displayName: "Akhil Menon",
    headline: "Product Designer and UX Researcher",
    bio: "Independent product designer helping B2B SaaS teams ship clear, trustworthy workflows. 7+ years across partner portals, onboarding, and operations tooling.",
    primaryCategory: "Product Design",
    secondaryCategory: "UX Research",
    skills: ["Product Design", "UX Research", "Figma", "Design Systems", "Prototyping", "Usability Testing"],
    portfolioItems: [
      { id: "PF-1", title: "Partner Portal Case Study", category: "Product Design", description: "Redesigned a partner onboarding portal reducing time-to-activate by 38%.", type: "case_study", url: "https://example.com/case/partner-portal", featured: true },
      { id: "PF-2", title: "Ops Console Refresh", category: "Product Design", description: "Operations console for a fintech, focused on queue triage and audit.", type: "case_study", url: "https://example.com/case/ops-console" },
      { id: "PF-3", title: "Onboarding Flow Research", category: "UX Research", description: "12 moderated interviews synthesised into a journey map.", type: "case_study" },
    ],
    availability: "available_now",
    responseTime: "Under 2 hours",
    preferredProjectSize: "₹40,000 - ₹1,50,000",
    preferredTimeline: "4 - 12 weeks",
    languages: ["English", "Malayalam", "Hindi"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed", "Portfolio reviewed", "Available now"],
    completedProjects: 38,
    rating: 4.9,
    responseTimeHours: 2,
    payoutReadiness: "approved",
    payoutDetails: { beneficiaryName: "Akhil Menon", accountNumberMasked: "••••4821", ifscMasked: "HDFC••••", bankName: "HDFC Bank" },
    feeFrom: 25000,
  },
  {
    userId: "PRO-2099",
    displayName: "Priya Nair",
    headline: "Frontend Engineer (React/Next.js)",
    bio: "Frontend engineer specialising in accessible, production-grade React and Next.js apps for SaaS.",
    primaryCategory: "Frontend Engineering",
    secondaryCategory: "Web Development",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Accessibility", "Testing"],
    portfolioItems: [
      { id: "PF-10", title: "SaaS Dashboard Kit", category: "Frontend Engineering", description: "Open-source dashboard kit with 40+ accessible components.", type: "case_study", featured: true },
    ],
    availability: "available_now",
    responseTime: "Under 4 hours",
    preferredProjectSize: "₹60,000 - ₹2,00,000",
    preferredTimeline: "6 - 16 weeks",
    languages: ["English", "Malayalam"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed", "Portfolio reviewed", "Available now"],
    completedProjects: 22,
    rating: 4.8,
    responseTimeHours: 4,
    payoutReadiness: "approved",
    payoutDetails: { beneficiaryName: "Priya Nair", accountNumberMasked: "••••2290", ifscMasked: "ICIC••••", bankName: "ICICI Bank" },
    feeFrom: 40000,
  },
  {
    userId: "PRO-2101",
    displayName: "Rahul Verma",
    headline: "Brand & Identity Designer",
    bio: "Brand identity systems for early-stage startups. Logo, type, color, guidelines.",
    primaryCategory: "Brand & Identity",
    skills: ["Brand Identity", "Logo Design", "Typography", "Illustration"],
    portfolioItems: [
      { id: "PF-20", title: "Fintech Brand System", category: "Brand & Identity", description: "Full identity system for a neo-bank.", type: "case_study", featured: true },
    ],
    availability: "paused",
    responseTime: "Under 1 day",
    preferredProjectSize: "₹30,000 - ₹1,00,000",
    preferredTimeline: "2 - 6 weeks",
    languages: ["English", "Hindi"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed", "Portfolio reviewed"],
    completedProjects: 15,
    rating: 4.7,
    responseTimeHours: 24,
    payoutReadiness: "approved",
    payoutDetails: { beneficiaryName: "Rahul Verma", accountNumberMasked: "••••1180", ifscMasked: "SBIN••••", bankName: "State Bank of India" },
    feeFrom: 30000,
  },
  {
    userId: "PRO-2102",
    displayName: "Sara Khan",
    headline: "UX Researcher",
    bio: "Mixed-methods UX researcher. Interviews, surveys, usability testing, synthesis.",
    primaryCategory: "UX Research",
    skills: ["User Interviews", "Surveys", "Usability Testing", "Synthesis", "Journey Mapping"],
    portfolioItems: [],
    availability: "available_now",
    responseTime: "Under 6 hours",
    preferredProjectSize: "₹25,000 - ₹80,000",
    preferredTimeline: "2 - 8 weeks",
    languages: ["English", "Hindi"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed"],
    completedProjects: 6,
    rating: 4.6,
    responseTimeHours: 6,
    payoutReadiness: "under_review",
    feeFrom: 25000,
  },
];

export const SEED_BUYER_PROFILES: BuyerProfile[] = [
  {
    userId: "BUY-1042",
    displayName: "Northstar Labs",
    companyDescription: "B2B SaaS company building partner enablement tooling. We hire vetted independent pros for product, design, and engineering work.",
    industry: "B2B SaaS",
    website: "https://northstarlabs.example",
    hiringCategories: ["Product Design", "Frontend Engineering", "UX Research"],
    logoColor: "#0F766E",
    orgDetails: { companyName: "Northstar Labs Pvt Ltd", billingAddress: "Kochi, Kerala, India", gstin: "32ABCDE1234F1Z5", billingContact: "ops@northstarlabs.example" },
    publicVisibility: true,
  },
  {
    userId: "BUY-1050",
    displayName: "Verdant Retail",
    companyDescription: "Omnichannel retail. Hiring for brand, content, and analytics.",
    industry: "Retail",
    hiringCategories: ["Brand & Identity", "Content Writing"],
    logoColor: "#15803D",
    orgDetails: { companyName: "Verdant Retail Pvt Ltd", billingAddress: "Bengaluru, Karnataka, India", billingContact: "finance@verdant.example" },
    publicVisibility: true,
  },
];

function ms(i: number): Milestone {
  return {
    id: `M-${i + 1}`,
    index: i + 1,
    label: `M${i + 1}`,
    description: ["Discovery & wireframes", "Hi-fi design", "Prototype & usability", "Handoff & docs"][i] || `Milestone ${i + 1}`,
    proFee: [34200, 20000, 15800, 10000][i] || 0,
    status: i === 0 ? "funding_pending" : "not_started",
    acceptanceCriteria: [
      "Stakeholder aligned wireframes",
      "Hi-fi screens approved",
      "Prototype passes usability test",
      "Design tokens & docs delivered",
    ][i] ? [`${i + 1}.1 Sign-off recorded`] : [],
    versions: [],
  };
}

export const SEED_BRIEFS: Brief[] = [
  {
    id: "BRF-0892",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    title: "Build a secure partner onboarding portal",
    category: "Web Development",
    objective: "Design and build a secure portal for partners to onboard, verify, and manage their integration with our SaaS.",
    deliverables: ["Onboarding flow", "Verification screens", "Admin review console", "Design system tokens"],
    acceptanceCriteria: ["WCAG 2.1 AA", "Responsive 390/1440", "Documented design tokens", "Usability tested with 5 partners"],
    exclusions: ["No SEO optimization", "No ongoing hosting support"],
    budget: 80000,
    timeline: "8 weeks",
    visibility: "open",
    status: "active",
    createdAt: "2025-01-10T09:00:00Z",
    applicants: 3,
  },
  {
    id: "BRF-0901",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    title: "UX research for partner portal - 12 interviews",
    category: "UX Research",
    objective: "Conduct 12 moderated interviews with existing partners and synthesise into a journey map.",
    deliverables: ["Interview script", "12 interview recordings", "Journey map", "Top 10 insights"],
    acceptanceCriteria: ["Recordings transcribed", "Journey map reviewed by PM"],
    exclusions: ["No quantitative survey"],
    budget: 60000,
    timeline: "4 weeks",
    visibility: "open",
    status: "active",
    createdAt: "2025-01-15T09:00:00Z",
    applicants: 2,
  },
  {
    id: "BRF-0915",
    buyerId: "BUY-1050",
    buyerName: "Verdant Retail",
    title: "Brand identity for new retail sub-brand",
    category: "Brand & Identity",
    objective: "Logo, color, type, and basic guidelines for a new sub-brand.",
    deliverables: ["Logo set", "Color palette", "Type system", "1-page guidelines"],
    acceptanceCriteria: ["3 logo routes explored", "Final delivered in SVG + PNG"],
    exclusions: ["No packaging design"],
    budget: 45000,
    timeline: "3 weeks",
    visibility: "open",
    status: "approaching_inactivity",
    createdAt: "2024-12-20T09:00:00Z",
    applicants: 1,
  },
  {
    id: "BRF-0920",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    title: "Private: Design ops audit (invite only)",
    category: "Product Design",
    objective: "Audit our design ops and propose improvements.",
    deliverables: ["Audit report", "30/60/90 plan"],
    acceptanceCriteria: ["Reviewed by Head of Design"],
    exclusions: ["No implementation"],
    budget: 35000,
    timeline: "2 weeks",
    visibility: "private",
    status: "active",
    createdAt: "2025-01-18T09:00:00Z",
    applicants: 0,
  },
];

export const SEED_PROPOSALS: Proposal[] = [
  {
    id: "PRP-4217",
    briefId: "BRF-0892",
    briefTitle: "Build a secure partner onboarding portal",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    proHeadline: "Product Designer and UX Researcher",
    proposedFee: 85000,
    coverLetter: "I have shipped two partner portals for B2B SaaS and can bring a proven onboarding pattern library. I propose a 4-milestone plan starting with discovery wireframes, then hi-fi, prototype, and handoff. I will not begin work until QuickQuid confirms milestone funding.",
    deliveryApproach: "Discovery (1w) -> Wireframes (2w) -> Hi-fi (2w) -> Prototype + usability (2w) -> Handoff (1w)",
    availability: "Available now",
    evidence: ["Partner Portal Case Study", "Ops Console Refresh"],
    status: "shortlisted",
    createdAt: "2025-01-12T10:00:00Z",
  },
  {
    id: "PRP-4218",
    briefId: "BRF-0892",
    briefTitle: "Build a secure partner onboarding portal",
    proId: "PRO-2099",
    proName: "Priya Nair",
    proHeadline: "Frontend Engineer (React/Next.js)",
    proposedFee: 92000,
    coverLetter: "I can build the portal in Next.js with accessibility-first components and a documented token system. 6 years of production React experience.",
    deliveryApproach: "Sprint-based, 2-week cycles with demos.",
    availability: "Available now",
    evidence: ["SaaS Dashboard Kit"],
    status: "pending",
    createdAt: "2025-01-13T11:00:00Z",
  },
  {
    id: "PRP-4219",
    briefId: "BRF-0901",
    briefTitle: "UX research for partner portal - 12 interviews",
    proId: "PRO-2102",
    proName: "Sara Khan",
    proHeadline: "UX Researcher",
    proposedFee: 58000,
    coverLetter: "Mixed-methods researcher. I can run 12 moderated interviews and synthesise into a journey map with prioritised insights.",
    deliveryApproach: "Script (3d) -> Recruitment (5d) -> Interviews (8d) -> Synthesis (5d) -> Readout (1d)",
    availability: "Available now",
    evidence: [],
    status: "pending",
    createdAt: "2025-01-16T10:00:00Z",
  },
];

export const SEED_CONTRACTS: Contract[] = [
  {
    id: "QQ-0892",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    briefId: "BRF-0892",
    briefTitle: "Build a secure partner onboarding portal",
    scope: "Design a secure partner onboarding portal: onboarding flow, verification screens, admin review console, design system tokens. WCAG 2.1 AA, responsive 390/1440, usability tested with 5 partners.",
    exclusions: ["No SEO optimization", "No ongoing hosting support"],
    timeline: "8 weeks",
    totalProFee: 80000,
    revisions: 2,
    milestones: [ms(0), ms(1), ms(2), ms(3)],
    status: "offer_accepted_pending_funding",
    createdAt: "2025-01-14T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-1",
  },
  {
    id: "QQ-0680",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    briefId: "BRF-0892",
    briefTitle: "Ops console redesign",
    scope: "Redesign the internal ops console for queue triage and audit. 6 key screens, design tokens, handoff docs.",
    exclusions: ["No development", "No SEO"],
    timeline: "4 weeks",
    totalProFee: 55000,
    revisions: 2,
    milestones: [
      { id: "M-1", index: 1, label: "M1", description: "Discovery & wireframes", proFee: 20000, status: "payout_processed", acceptanceCriteria: ["Stakeholder aligned wireframes"], versions: [{ id: "V-1", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-02T10:00:00Z", link: "https://figma.com/file/wireframes", changeNote: "Initial wireframes" }] },
      { id: "M-2", index: 2, label: "M2", description: "Hi-fi design", proFee: 20000, status: "payout_processed", acceptanceCriteria: ["Hi-fi screens approved"], versions: [{ id: "V-2", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-09T10:00:00Z", link: "https://figma.com/file/hifi", changeNote: "Hi-fi screens" }] },
      { id: "M-3", index: 3, label: "M3", description: "Handoff & docs", proFee: 15000, status: "payout_processed", acceptanceCriteria: ["Design tokens & docs delivered"], versions: [{ id: "V-3", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-16T10:00:00Z", link: "https://figma.com/file/handoff", changeNote: "Final handoff" }] },
    ],
    status: "completed",
    createdAt: "2024-12-20T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-3",
  },
];

export const SEED_PAYMENTS: PaymentEvidence[] = [
  {
    id: "PAY-0892",
    contractId: "QQ-0892",
    milestoneId: "M-1",
    milestoneLabel: "M1",
    amountDue: 34200,
    utr: "UTR982341771",
    method: "NEFT",
    date: "2025-01-14T11:30:00Z",
    status: "under_admin_verification",
    targetReviewHours: 24,
    submittedAt: "2025-01-14T11:35:00Z",
  },
];

export const SEED_PAYOUTS: Payout[] = [
  {
    id: "PO-5001",
    contractId: "QQ-0700",
    proId: "PRO-2099",
    proName: "Priya Nair",
    milestoneLabel: "M2",
    proFee: 20000,
    commission: 0,
    netPayout: 20000,
    status: "queued",
    beneficiaryToken: "BNF-7781",
    queuedAt: "2025-01-08T10:00:00Z",
    slipAvailable: false,
  },
  {
    id: "PO-4990",
    contractId: "QQ-0650",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    milestoneLabel: "M3",
    proFee: 25000,
    commission: 0,
    statutoryWithholding: 2500,
    netPayout: 22500,
    status: "processed",
    reference: "NEFT-885511002",
    beneficiaryToken: "BNF-6612",
    queuedAt: "2024-12-28T10:00:00Z",
    processedAt: "2024-12-29T16:20:00Z",
    slipAvailable: true,
  },
  {
    id: "PO-5010",
    contractId: "QQ-0720",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    milestoneLabel: "M2",
    proFee: 18000,
    commission: 0,
    netPayout: 18000,
    status: "failed",
    beneficiaryToken: "BNF-6612",
    queuedAt: "2025-01-09T10:00:00Z",
    failureReason: "Beneficiary account number mismatch. Bank returned NEFT-771200441 as invalid.",
    slipAvailable: false,
  },
];

export const SEED_REFUNDS: Refund[] = [
  {
    id: "RF-3001",
    contractId: "QQ-0610",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    amount: 15000,
    reason: "Mutual cancellation before work start",
    status: "requested",
    beneficiaryToken: "BNF-1042",
    createdAt: "2025-01-05T09:00:00Z",
  },
];

export const SEED_DISPUTES: Dispute[] = [
  {
    id: "DSP-7001",
    contractId: "QQ-0650",
    raisedBy: "buyer",
    raisedByName: "Northstar Labs",
    category: "quality_bugs",
    affectedMilestone: "M3",
    requestedResolution: "Partial refund - deliverable did not meet acceptance criterion 3.2",
    narrative: "The delivered brand guidelines missed the type scale section agreed in acceptance criteria.",
    evidence: ["Guideline_v2.pdf", "Acceptance_criteria.docx"],
    desiredOutcome: "₹7,000 refund and revised guidelines",
    status: "under_mediation",
    counterclaim: "Pro states the type scale was delivered in a separate file.",
    createdAt: "2025-01-02T09:00:00Z",
    slaOpenedAt: "2025-01-02T09:00:00Z",
    owner: "Deepa R (Risk T3)",
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "REV-1001",
    contractId: "QQ-0680",
    fromUserId: "BUY-1042",
    fromName: "Northstar Labs",
    toRole: "pro",
    rating: 5,
    comment: "Akhil delivered the ops console redesign ahead of schedule. The design tokens and handoff docs were exceptional. Would rehire.",
    visible: true,
    bothSubmitted: true,
    createdAt: "2025-01-17T10:00:00Z",
  },
  {
    id: "REV-1002",
    contractId: "QQ-0680",
    fromUserId: "PRO-2088",
    fromName: "Akhil Menon",
    toRole: "buyer",
    rating: 5,
    comment: "Clear brief, fast feedback, prompt milestone acceptance. Great client to work with.",
    visible: true,
    bothSubmitted: true,
    createdAt: "2025-01-17T12:00:00Z",
  },
];

export const SEED_TICKETS: SupportTicket[] = [
  {
    id: "TKT-9001",
    userId: "BUY-1042",
    userName: "Northstar Labs",
    category: "payment",
    subject: "UTR not matching in bank statement",
    description: "I submitted UTR982341771 but it is showing under verification for over 24h.",
    attachedContext: { contractId: "QQ-0892", paymentReference: "PAY-0892", status: "Under Admin Verification", latestEvent: "Evidence submitted 2025-01-14" },
    status: "assigned",
    owner: "Meera S (Support T1)",
    createdAt: "2025-01-15T08:00:00Z",
    messages: [
      { from: "user", text: "UTR not matching in bank statement", at: "2025-01-15T08:00:00Z" },
      { from: "admin", text: "Thanks, I am escalating to Finance for matcher review.", at: "2025-01-15T09:30:00Z" },
    ],
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  { id: "N-1", userId: "BUY-1042", type: "proposal_received", title: "New proposal on BRF-0892", body: "Akhil Menon submitted a proposal (₹85,000).", link: "buyer_brief_detail?briefId=BRF-0892", read: false, createdAt: "2025-01-12T10:01:00Z" },
  { id: "N-2", userId: "BUY-1042", type: "payment_submitted", title: "Payment evidence submitted", body: "PAY-0892 is under Admin verification. Target: 24h.", link: "buyer_payment?contractId=QQ-0892", read: false, createdAt: "2025-01-14T11:36:00Z" },
  { id: "N-3", userId: "PRO-2088", type: "contract_accepted", title: "Contract QQ-0892 accepted", body: "Northstar Labs accepted your offer. Funding pending.", link: "pro_contract?contractId=QQ-0892", read: false, createdAt: "2025-01-14T09:05:00Z" },
  { id: "N-4", userId: "PRO-2088", type: "sla_warning", title: "Do not begin work yet", body: "Payment verification pending for M1. Do not begin work until QuickQuid confirms funding.", link: "pro_contract?contractId=QQ-0892", read: false, createdAt: "2025-01-14T11:37:00Z" },
  { id: "N-5", userId: "FIN-F01", type: "payment_submitted", title: "Payment verification queued", body: "PAY-0892 awaiting matcher review.", link: "admin_payments", read: false, createdAt: "2025-01-14T11:36:00Z" },
  { id: "N-6", userId: "ADM-S01", type: "dispute_opened", title: "New dispute DSP-7001", body: "Quality/bugs dispute on QQ-0650.", link: "admin_disputes", read: false, createdAt: "2025-01-02T09:01:00Z" },
];

export const SEED_AUDIT: AuditEvent[] = [
  { id: "A-1", adminId: "FIN-F01", adminRole: "finance", action: "Payment confirmed", entity: "Payment", entityId: "PAY-0612", oldStatus: "Under Admin Verification", newStatus: "Payment Confirmed", timestamp: "2024-12-20T14:00:00Z", reason: "UTR matched bank evidence" },
  { id: "A-2", adminId: "FIN-F01", adminRole: "finance", action: "Payout authorized", entity: "Payout", entityId: "PO-4990", oldStatus: "Maker Confirmed", newStatus: "Checker Authorized", timestamp: "2024-12-28T15:00:00Z", reason: "Maker-checker threshold met" },
  { id: "A-3", adminId: "RSK-R01", adminRole: "risk", action: "Masked reveal", entity: "KYC", entityId: "KYC-2200", timestamp: "2024-12-22T10:00:00Z", reason: "Duplicate device signal investigation", maskedReveal: true },
  { id: "A-4", adminId: "RSK-R01", adminRole: "risk", action: "Account suspended", entity: "User", entityId: "PRO-1950", oldStatus: "Active", newStatus: "Suspended", timestamp: "2024-11-10T12:00:00Z", reason: "Repeat circumvention policy violation" },
];

export const SEED_KYC: KycSubmission[] = [
  {
    id: "KYC-2201",
    userId: "PRO-2102",
    userName: "Sara Khan",
    role: "pro",
    identityDocName: "aadhaar.jpg",
    identityDocStatus: "uploaded",
    panMasked: "AB•••••CD",
    accountNumberMasked: "••••3344",
    ifscMasked: "HDFC••••",
    beneficiaryName: "Sara Khan",
    status: "under_review",
    submittedAt: "2025-01-16T09:00:00Z",
  },
  {
    id: "KYC-2202",
    userId: "PRO-2088",
    userName: "Akhil Menon",
    role: "pro",
    identityDocName: "pan.jpg",
    identityDocStatus: "uploaded",
    panMasked: "AK•••••PM",
    accountNumberMasked: "••••4821",
    ifscMasked: "HDFC••••",
    beneficiaryName: "Akhil Menon",
    status: "approved",
    submittedAt: "2024-10-01T09:00:00Z",
    resolvedAt: "2024-10-01T20:00:00Z",
  },
  {
    id: "KYC-2203",
    userId: "PRO-2110",
    userName: "Test Pro (risk)",
    role: "pro",
    identityDocName: "id.png",
    identityDocStatus: "uploaded",
    panMasked: "TT•••••PP",
    accountNumberMasked: "••••9900",
    ifscMasked: "YESB••••",
    beneficiaryName: "Test Pro",
    status: "under_review",
    submittedAt: "2025-01-17T09:00:00Z",
    riskFlag: { signal: "device or network pattern matches a previously suspended account", confidence: 0.78, priorAccountStatus: "Suspended", hashedSignal: "h_8f2a91c4d7" },
  },
  {
    id: "KYC-2204",
    userId: "PRO-2111",
    userName: "Blurry Doc Pro",
    role: "pro",
    identityDocName: "id_blurry.jpg",
    identityDocStatus: "rejected",
    panMasked: "BD•••••PP",
    accountNumberMasked: "••••1234",
    ifscMasked: "ICIC••••",
    beneficiaryName: "Blurry Doc Pro",
    status: "rejected",
    submittedAt: "2025-01-10T09:00:00Z",
    resolvedAt: "2025-01-11T09:00:00Z",
    rejectionReason: "Image is too blurry. Upload a clearer document.",
  },
];

export const SEED_GIGS: GigDraft[] = [
  {
    id: "GIG-3001",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    title: "Design system audit & token delivery",
    category: "Product Design",
    subcategory: "Design Systems",
    tags: ["design systems", "tokens", "figma"],
    shortDescription: "Audit your existing product UI and deliver a documented design token set.",
    detailedDescription: "I will audit your product UI across 10 key screens, identify inconsistencies, and deliver a documented design token set in Figma + JSON. QuickQuid deducts 0% commission from your fee.",
    includedItems: ["Audit report", "Token JSON", "Figma library"],
    exclusions: ["No implementation in code"],
    deliverableFormat: "Figma link + JSON",
    revisions: 2,
    deliveryTimeline: "10 days",
    buyerRequirements: ["Provide Figma access", "Share 3 priority screens"],
    evidence: ["Partner Portal Case Study"],
    coverImageColor: "#7C3AED",
    packageName: "Standard",
    proFee: 25000,
    availability: true,
    maxConcurrentOrders: 2,
    status: "approved_live",
    createdAt: "2025-01-09T09:00:00Z",
    views: 142,
    requests: 6,
    rating: 4.9,
  },
  {
    id: "GIG-3002",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    title: "Partner onboarding flow - design only",
    category: "Product Design",
    subcategory: "Onboarding",
    tags: ["onboarding", "saas", "ux"],
    shortDescription: "End-to-end partner onboarding flow design with usability testing.",
    detailedDescription: "Discovery, wireframes, hi-fi, prototype, and 5-partner usability test.",
    includedItems: ["Wireframes", "Hi-fi screens", "Prototype", "Usability report"],
    exclusions: ["No development", "No SEO"],
    deliverableFormat: "Figma link",
    revisions: 2,
    deliveryTimeline: "4 weeks",
    buyerRequirements: ["Stakeholder availability for discovery"],
    evidence: [],
    coverImageColor: "#0891B2",
    packageName: "Standard",
    proFee: 60000,
    availability: true,
    maxConcurrentOrders: 1,
    status: "under_review",
    createdAt: "2025-01-18T09:00:00Z",
    views: 22,
    requests: 1,
  },
  {
    id: "GIG-3003",
    proId: "PRO-2099",
    proName: "Priya Nair",
    title: "Next.js landing page",
    category: "Frontend Engineering",
    subcategory: "Landing Pages",
    tags: ["nextjs", "react", "tailwind"],
    shortDescription: "Production-grade, accessible Next.js landing page.",
    detailedDescription: "A responsive, accessible landing page in Next.js + Tailwind. Lighthouse 95+.",
    includedItems: ["Source code", "Deployment guide"],
    exclusions: ["No backend", "No CMS integration"],
    deliverableFormat: "GitHub repo",
    revisions: 1,
    deliveryTimeline: "7 days",
    buyerRequirements: ["Provide brand assets"],
    evidence: ["SaaS Dashboard Kit"],
    coverImageColor: "#0EA5E9",
    packageName: "Basic",
    proFee: 30000,
    availability: true,
    maxConcurrentOrders: 2,
    status: "changes_requested",
    createdAt: "2025-01-19T09:00:00Z",
    views: 18,
    requests: 0,
    moderationReason: "Missing deliverable: deployment guide unclear",
  },
];

export const SEED_OFFLINE_INSTRUMENTS: OfflineInstrument[] = [
  {
    id: "OI-4001",
    contractRef: "QQ-0620",
    instrumentType: "Cheque",
    bank: "HDFC Bank",
    instrumentNumber: "CHQ-551200",
    amount: 50000,
    receivedDate: "2025-01-03",
    expectedSettlement: "2025-01-06",
    owner: "Arjun K (Finance T2)",
    status: "dishonoured",
  },
];

export const SEED_TRUST_CASES: TrustSafetyCase[] = [
  {
    id: "TS-6001",
    complainant: "Northstar Labs",
    affectedEntity: "Pro profile PRO-1950",
    allegation: "Pro attempted to take payment off-platform via shared UPI link in messages.",
    evidence: ["Message screenshot", "Circumvention log"],
    urgency: "high",
    owner: "Deepa R (Risk T3)",
    status: "investigating",
    actionHistory: [
      { action: "Case opened", at: "2025-01-04T10:00:00Z", by: "System" },
      { action: "Assigned to Risk T3", at: "2025-01-04T10:05:00Z", by: "Meera S (Support T1)" },
    ],
    createdAt: "2025-01-04T10:00:00Z",
  },
];

export const ADMIN_NOTES = [
  "v0.1 prototype: no wallet, no automated escrow, no auto-payout API. All payouts are manually processed.",
  "Buyer fee is fixed at 14% for the controlled beta. The 13% standard and earned-rate ladder are future and must NOT be shown as active.",
  "Pro commission is 0%. Pro fee and Buyer fee are always separate line items.",
  "Maximum 4 milestones per contract in v0.1 due to manual payment verification.",
  "Taxes shown as 'Calculated by Finance if applicable' - never hardcode TDS/GST/TCS rates.",
  "Sensitive data (PAN, bank account, IFSC) is masked by default. Reveal requires reason + audit event.",
  "Role switcher (bottom-left) is restricted to prototype mode for demo/QA only.",
  "All money-movement actions go through maker-checker for Finance and produce audit events.",
];
