import type {
  User, ProProfile, BuyerProfile, Brief, Proposal, Contract,
  PaymentEvidence, Payout, Refund, Dispute, Review, SupportTicket,
  NotificationItem, AuditEvent, KycSubmission, GigDraft, OfflineInstrument,
  TrustSafetyCase, Milestone, PriorityBoost,
} from "./types";

export const SEED_USERS: User[] = [
  { id: "BUY-1042", role: "buyer", name: "Northstar Labs", email: "ops@northstarlabs.example", headline: "B2B SaaS company", avatarColor: "#0F766E", location: "Kochi, India", industry: "B2B SaaS", verification: "QuickQuid Verified", verificationStatus: "approved", verifiedAt: "2024-09-21T12:00:00Z", verifiedBy: "ADM-S01" },
  { id: "PRO-2088", role: "pro", name: "Akhil Menon", email: "akhil@example.com", headline: "Product Designer and UX Researcher", avatarColor: "#7C3AED", location: "Bengaluru, India", industry: "Design", verification: "QuickQuid Verified", verificationStatus: "approved", verifiedAt: "2024-10-01T20:00:00Z", verifiedBy: "ADM-S01" },
  { id: "PRO-2099", role: "pro", name: "Priya Nair", email: "priya@example.com", headline: "Frontend Engineer (React/Next.js)", avatarColor: "#0891B2", location: "Kochi, India", industry: "Engineering", verification: "QuickQuid Verified", verificationStatus: "approved", verifiedAt: "2024-10-06T14:00:00Z", verifiedBy: "ADM-S01" },
  { id: "PRO-2101", role: "pro", name: "Rahul Verma", email: "rahul@example.com", headline: "Brand & Identity Designer", avatarColor: "#DB2777", location: "Mumbai, India", industry: "Design", verification: "QuickQuid Verified", verificationStatus: "approved", verifiedAt: "2024-10-10T11:00:00Z", verifiedBy: "ADM-S01" },
  { id: "PRO-2102", role: "pro", name: "Sara Khan", email: "sara@example.com", headline: "UX Researcher", avatarColor: "#CA8A04", location: "Pune, India", industry: "Research", verification: "Pending review", verificationStatus: "under_review" },
  { id: "BUY-1050", role: "buyer", name: "Verdant Retail", email: "finance@verdant.example", headline: "Omnichannel retail", avatarColor: "#15803D", location: "Bengaluru, India", industry: "Retail", verification: "QuickQuid Verified", verificationStatus: "approved", verifiedAt: "2024-09-25T13:00:00Z", verifiedBy: "ADM-S01" },
  { id: "ADM-S01", role: "admin_support", name: "Meera S (Support T1)", email: "meera@quickquid.example", avatarColor: "#475569", verification: "Staff", verificationStatus: "approved" },
  { id: "FIN-F01", role: "finance", name: "Arjun K (Finance T2)", email: "arjun@quickquid.example", avatarColor: "#1E40AF", verification: "Staff", verificationStatus: "approved" },
  { id: "RSK-R01", role: "risk", name: "Deepa R (Risk T3)", email: "deepa@quickquid.example", avatarColor: "#9F1239", verification: "Staff", verificationStatus: "approved" },
  { id: "OPS-O01", role: "ops_manager", name: "Vikram T (Ops Manager)", email: "vikram@quickquid.example", avatarColor: "#334155", verification: "Staff", verificationStatus: "approved" },
];

export const SEED_PRO_PROFILES: ProProfile[] = [
  {
    userId: "PRO-2088",
    displayName: "Akhil Menon",
    headline: "Product Designer and UX Researcher",
    bio: "Independent product designer helping B2B SaaS teams ship clear, trustworthy workflows. 7+ years across partner portals, onboarding, and operations tooling.",
    primaryCategory: "Product Design",
    secondaryCategory: "UX Research",
    skills: ["Product Design", "UX Research", "Figma", "Design Systems", "Prototyping", "Usability Testing"],
    skillVerifications: [
      { skill: "Product Design", evidence: "Partner Portal and Ops Console case studies", status: "approved", submittedAt: "2024-09-30T09:00:00Z", reviewedAt: "2024-10-01T20:00:00Z", reviewedBy: "ADM-S01", reviewerNote: "Comparable product workflow evidence reviewed." },
      { skill: "UX Research", evidence: "Onboarding Flow Research case study", status: "approved", submittedAt: "2024-09-30T09:00:00Z", reviewedAt: "2024-10-01T20:00:00Z", reviewedBy: "ADM-S01", reviewerNote: "Research plan and synthesis evidence reviewed." },
    ],
    portfolioItems: [
      { id: "PF-1", title: "Partner Portal Case Study", category: "Product Design", description: "Redesigned a partner onboarding portal reducing time-to-activate by 38%.", type: "case_study", url: "https://example.com/case/partner-portal", imageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/62c63cd0aad8.png", featured: true },
      { id: "PF-2", title: "Ops Console Refresh", category: "Product Design", description: "Operations console for a fintech, focused on queue triage and audit.", type: "case_study", url: "https://example.com/case/ops-console", imageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/750fe92d211b.jpg" },
      { id: "PF-3", title: "Onboarding Flow Research", category: "UX Research", description: "12 moderated interviews synthesised into a journey map.", type: "case_study", imageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cb3a854cf497.png" },
    ],
    availability: "available_now",
    responseTime: "Under 2 hours",
    preferredProjectSize: "₹40,000 - ₹1,50,000",
    preferredTimeline: "4 - 12 weeks",
    languages: ["English", "Malayalam", "Hindi"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed", "Portfolio reviewed", "Available now"],
    completedProjects: 38,
    rating: 4.9,
    responseTimeHours: 2,
    payoutReadiness: "approved",
    onboardingStatus: "approved",
    onboardingSubmittedAt: "2024-09-30T09:00:00Z",
    payoutDetails: { beneficiaryName: "Akhil Menon", accountNumberMasked: "••••4821", ifscMasked: "HDFC••••", bankName: "HDFC Bank" },
    feeFrom: 25000,
  },
  {
    userId: "PRO-2099",
    displayName: "Priya Nair",
    headline: "Frontend Engineer (React/Next.js)",
    bio: "Frontend engineer specialising in accessible, production-grade React and Next.js apps for SaaS.",
    primaryCategory: "Frontend Engineering",
    secondaryCategory: "Web Development",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Accessibility", "Testing"],
    skillVerifications: [
      { skill: "React", evidence: "SaaS Dashboard Kit", status: "approved", submittedAt: "2024-10-05T09:00:00Z", reviewedAt: "2024-10-06T14:00:00Z", reviewedBy: "ADM-S01", reviewerNote: "Repository and shipped interface evidence reviewed." },
      { skill: "Next.js", evidence: "Next.js Landing Page case study", status: "approved", submittedAt: "2024-10-05T09:00:00Z", reviewedAt: "2024-10-06T14:00:00Z", reviewedBy: "ADM-S01", reviewerNote: "Production build evidence reviewed." },
    ],
    portfolioItems: [
      { id: "PF-10", title: "SaaS Dashboard Kit", category: "Frontend Engineering", description: "Open-source dashboard kit with 40+ accessible components.", type: "case_study", imageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9628ecf06ad9.jpg", featured: true },
      { id: "PF-11", title: "Next.js Landing Page", category: "Frontend Engineering", description: "High-converting landing page with Lighthouse 98+.", type: "case_study", imageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/1494eb483574.png" },
    ],
    availability: "available_now",
    responseTime: "Under 4 hours",
    preferredProjectSize: "₹60,000 - ₹2,00,000",
    preferredTimeline: "6 - 16 weeks",
    languages: ["English", "Malayalam"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed", "Portfolio reviewed", "Available now"],
    completedProjects: 22,
    rating: 4.8,
    responseTimeHours: 4,
    payoutReadiness: "approved",
    onboardingStatus: "approved",
    onboardingSubmittedAt: "2024-10-05T09:00:00Z",
    payoutDetails: { beneficiaryName: "Priya Nair", accountNumberMasked: "••••2290", ifscMasked: "ICIC••••", bankName: "ICICI Bank" },
    feeFrom: 40000,
  },
  {
    userId: "PRO-2101",
    displayName: "Rahul Verma",
    headline: "Brand & Identity Designer",
    bio: "Brand identity systems for early-stage startups. Logo, type, color, guidelines.",
    primaryCategory: "Brand & Identity",
    skills: ["Brand Identity", "Logo Design", "Typography", "Illustration"],
    skillVerifications: [
      { skill: "Brand Identity", evidence: "Fintech Brand System", status: "approved", submittedAt: "2024-10-09T09:00:00Z", reviewedAt: "2024-10-10T11:00:00Z", reviewedBy: "ADM-S01", reviewerNote: "Identity system and application evidence reviewed." },
    ],
    portfolioItems: [
      { id: "PF-20", title: "Fintech Brand System", category: "Brand & Identity", description: "Full identity system for a neo-bank.", type: "case_study", imageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ab448629fbb2.jpg", featured: true },
      { id: "PF-21", title: "Logo Collection", category: "Brand & Identity", description: "Various logo designs for startups.", type: "image", imageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9c721d2bd294.jpg" },
    ],
    availability: "paused",
    responseTime: "Under 1 day",
    preferredProjectSize: "₹30,000 - ₹1,00,000",
    preferredTimeline: "2 - 6 weeks",
    languages: ["English", "Hindi"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed", "Portfolio reviewed"],
    completedProjects: 15,
    rating: 4.7,
    responseTimeHours: 24,
    payoutReadiness: "approved",
    onboardingStatus: "approved",
    onboardingSubmittedAt: "2024-10-09T09:00:00Z",
    payoutDetails: { beneficiaryName: "Rahul Verma", accountNumberMasked: "••••1180", ifscMasked: "SBIN••••", bankName: "State Bank of India" },
    feeFrom: 30000,
  },
  {
    userId: "PRO-2102",
    displayName: "Sara Khan",
    headline: "UX Researcher",
    bio: "Mixed-methods UX researcher. Interviews, surveys, usability testing, synthesis.",
    primaryCategory: "UX Research",
    skills: ["User Interviews", "Surveys", "Usability Testing", "Synthesis", "Journey Mapping"],
    skillVerifications: [
      { skill: "User Interviews", evidence: "Interview guide and anonymized synthesis sample", status: "under_review", submittedAt: "2025-01-16T09:00:00Z" },
      { skill: "Usability Testing", evidence: "Moderated test plan and findings sample", status: "under_review", submittedAt: "2025-01-16T09:00:00Z" },
    ],
    portfolioItems: [],
    availability: "available_now",
    responseTime: "Under 6 hours",
    preferredProjectSize: "₹25,000 - ₹80,000",
    preferredTimeline: "2 - 8 weeks",
    languages: ["English", "Hindi"],
    timeZone: "IST (UTC+5:30)",
    publicVisibility: true,
    trustSignals: ["Identity reviewed"],
    completedProjects: 6,
    rating: 4.6,
    responseTimeHours: 6,
    payoutReadiness: "under_review",
    onboardingStatus: "under_review",
    onboardingSubmittedAt: "2025-01-16T09:00:00Z",
    feeFrom: 25000,
  },
];

export const SEED_BUYER_PROFILES: BuyerProfile[] = [
  {
    userId: "BUY-1042",
    displayName: "Northstar Labs",
    companyDescription: "B2B SaaS company building partner enablement tooling. We hire vetted independent pros for product, design, and engineering work.",
    industry: "B2B SaaS",
    website: "https://northstarlabs.example",
    hiringCategories: ["Product Design", "Frontend Engineering", "UX Research"],
    logoColor: "#0F766E",
    orgDetails: { companyName: "Northstar Labs Pvt Ltd", billingAddress: "Kochi, Kerala, India", gstin: "32ABCDE1234F1Z5", billingContact: "ops@northstarlabs.example" },
    publicVisibility: true,
  },
  {
    userId: "BUY-1050",
    displayName: "Verdant Retail",
    companyDescription: "Omnichannel retail. Hiring for brand, content, and analytics.",
    industry: "Retail",
    hiringCategories: ["Brand & Identity", "Content Writing"],
    logoColor: "#15803D",
    orgDetails: { companyName: "Verdant Retail Pvt Ltd", billingAddress: "Bengaluru, Karnataka, India", billingContact: "finance@verdant.example" },
    publicVisibility: true,
  },
];

function ms(i: number): Milestone {
  return {
    id: `M-${i + 1}`,
    index: i + 1,
    label: `M${i + 1}`,
    description: ["Discovery & wireframes", "Hi-fi design", "Prototype & usability", "Handoff & docs"][i] || `Milestone ${i + 1}`,
    proFee: [34200, 20000, 15800, 10000][i] || 0,
    status: i === 0 ? "funding_pending" : "not_started",
    acceptanceCriteria: [
      "Stakeholder aligned wireframes",
      "Hi-fi screens approved",
      "Prototype passes usability test",
      "Design tokens & docs delivered",
    ][i] ? [`${i + 1}.1 Sign-off recorded`] : [],
    versions: [],
  };
}

export const SEED_BRIEFS: Brief[] = [
  {
    id: "BRF-0892",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    title: "Build a secure partner onboarding portal",
    category: "Web Development",
    objective: "Design and build a secure portal for partners to onboard, verify, and manage their integration with our SaaS.",
    deliverables: ["Onboarding flow", "Verification screens", "Admin review console", "Design system tokens"],
    acceptanceCriteria: ["WCAG 2.1 AA", "Responsive 390/1440", "Documented design tokens", "Usability tested with 5 partners"],
    exclusions: ["No SEO optimization", "No ongoing hosting support"],
    budget: 80000,
    timeline: "8 weeks",
    visibility: "open",
    status: "active",
    createdAt: "2025-01-10T09:00:00Z",
    applicants: 3,
  },
  {
    id: "BRF-0901",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    title: "UX research for partner portal - 12 interviews",
    category: "UX Research",
    objective: "Conduct 12 moderated interviews with existing partners and synthesise into a journey map.",
    deliverables: ["Interview script", "12 interview recordings", "Journey map", "Top 10 insights"],
    acceptanceCriteria: ["Recordings transcribed", "Journey map reviewed by PM"],
    exclusions: ["No quantitative survey"],
    budget: 60000,
    timeline: "4 weeks",
    visibility: "open",
    status: "active",
    createdAt: "2025-01-15T09:00:00Z",
    applicants: 2,
  },
  {
    id: "BRF-0915",
    buyerId: "BUY-1050",
    buyerName: "Verdant Retail",
    title: "Brand identity for new retail sub-brand",
    category: "Brand & Identity",
    objective: "Logo, color, type, and basic guidelines for a new sub-brand.",
    deliverables: ["Logo set", "Color palette", "Type system", "1-page guidelines"],
    acceptanceCriteria: ["3 logo routes explored", "Final delivered in SVG + PNG"],
    exclusions: ["No packaging design"],
    budget: 45000,
    timeline: "3 weeks",
    visibility: "open",
    status: "approaching_inactivity",
    createdAt: "2024-12-20T09:00:00Z",
    applicants: 1,
  },
  {
    id: "BRF-0920",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    title: "Private: Design ops audit (invite only)",
    category: "Product Design",
    objective: "Audit our design ops and propose improvements.",
    deliverables: ["Audit report", "30/60/90 plan"],
    acceptanceCriteria: ["Reviewed by Head of Design"],
    exclusions: ["No implementation"],
    budget: 35000,
    timeline: "2 weeks",
    visibility: "private",
    status: "active",
    createdAt: "2025-01-18T09:00:00Z",
    applicants: 0,
  },
];

export const SEED_PROPOSALS: Proposal[] = [
  {
    id: "PRP-4217",
    briefId: "BRF-0892",
    briefTitle: "Build a secure partner onboarding portal",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    proHeadline: "Product Designer and UX Researcher",
    proposedFee: 85000,
    coverLetter: "I have shipped two partner portals for B2B SaaS and can bring a proven onboarding pattern library. I propose a 4-milestone plan starting with discovery wireframes, then hi-fi, prototype, and handoff. I will not begin work until QuickQuid confirms milestone funding.",
    deliveryApproach: "Discovery (1w) -> Wireframes (2w) -> Hi-fi (2w) -> Prototype + usability (2w) -> Handoff (1w)",
    availability: "Available now",
    evidence: ["Partner Portal Case Study", "Ops Console Refresh"],
    status: "shortlisted",
    createdAt: "2025-01-12T10:00:00Z",
  },
  {
    id: "PRP-4218",
    briefId: "BRF-0892",
    briefTitle: "Build a secure partner onboarding portal",
    proId: "PRO-2099",
    proName: "Priya Nair",
    proHeadline: "Frontend Engineer (React/Next.js)",
    proposedFee: 92000,
    coverLetter: "I can build the portal in Next.js with accessibility-first components and a documented token system. 6 years of production React experience.",
    deliveryApproach: "Sprint-based, 2-week cycles with demos.",
    availability: "Available now",
    evidence: ["SaaS Dashboard Kit"],
    status: "pending",
    createdAt: "2025-01-13T11:00:00Z",
  },
  {
    id: "PRP-4219",
    briefId: "BRF-0901",
    briefTitle: "UX research for partner portal - 12 interviews",
    proId: "PRO-2102",
    proName: "Sara Khan",
    proHeadline: "UX Researcher",
    proposedFee: 58000,
    coverLetter: "Mixed-methods researcher. I can run 12 moderated interviews and synthesise into a journey map with prioritised insights.",
    deliveryApproach: "Script (3d) -> Recruitment (5d) -> Interviews (8d) -> Synthesis (5d) -> Readout (1d)",
    availability: "Available now",
    evidence: [],
    status: "pending",
    createdAt: "2025-01-16T10:00:00Z",
  },
];

export const SEED_CONTRACTS: Contract[] = [
  {
    id: "QQ-0892",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    briefId: "BRF-0892",
    briefTitle: "Build a secure partner onboarding portal",
    scope: "Design a secure partner onboarding portal: onboarding flow, verification screens, admin review console, design system tokens. WCAG 2.1 AA, responsive 390/1440, usability tested with 5 partners.",
    exclusions: ["No SEO optimization", "No ongoing hosting support"],
    timeline: "8 weeks",
    totalProFee: 80000,
    revisions: 2,
    milestones: [ms(0), ms(1), ms(2), ms(3)],
    status: "offer_accepted_pending_funding",
    createdAt: "2025-01-14T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-1",
  },
  {
    id: "QQ-0680",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    briefId: "BRF-0892",
    briefTitle: "Ops console redesign",
    scope: "Redesign the internal ops console for queue triage and audit. 6 key screens, design tokens, handoff docs.",
    exclusions: ["No development", "No SEO"],
    timeline: "4 weeks",
    totalProFee: 55000,
    revisions: 2,
    milestones: [
      { id: "M-1", index: 1, label: "M1", description: "Discovery & wireframes", proFee: 20000, status: "payout_processed", acceptanceCriteria: ["Stakeholder aligned wireframes"], versions: [{ id: "V-1", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-02T10:00:00Z", link: "https://figma.com/file/wireframes", changeNote: "Initial wireframes" }] },
      { id: "M-2", index: 2, label: "M2", description: "Hi-fi design", proFee: 20000, status: "payout_processed", acceptanceCriteria: ["Hi-fi screens approved"], versions: [{ id: "V-2", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-09T10:00:00Z", link: "https://figma.com/file/hifi", changeNote: "Hi-fi screens" }] },
      { id: "M-3", index: 3, label: "M3", description: "Handoff & docs", proFee: 15000, status: "payout_processed", acceptanceCriteria: ["Design tokens & docs delivered"], versions: [{ id: "V-3", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-16T10:00:00Z", link: "https://figma.com/file/handoff", changeNote: "Final handoff" }] },
    ],
    status: "completed",
    createdAt: "2024-12-20T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-3",
  },
  {
    id: "QQ-0710",
    buyerId: "BUY-1050",
    buyerName: "Verdant Retail",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    briefId: "BRF-0915",
    briefTitle: "Brand identity for new retail sub-brand",
    scope: "Logo, color palette, typography, and basic brand guidelines for a new retail sub-brand.",
    exclusions: ["No packaging design", "No stationery"],
    timeline: "3 weeks",
    totalProFee: 45000,
    revisions: 2,
    milestones: [
      { id: "M-1", index: 1, label: "M1", description: "Logo concepts", proFee: 20000, status: "accepted", acceptanceCriteria: ["3 logo routes explored", "Final route selected"], versions: [{ id: "V-1", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-10T10:00:00Z", link: "https://figma.com/logo-concepts", changeNote: "3 logo concepts" }] },
      { id: "M-2", index: 2, label: "M2", description: "Color + type system", proFee: 15000, status: "in_review", acceptanceCriteria: ["Color palette approved", "Type pairing finalized"], versions: [{ id: "V-2", version: 1, status: "in_review", submitter: "pro", timestamp: "2025-01-18T10:00:00Z", link: "https://figma.com/color-type", changeNote: "Color palette + type system v1" }] },
      { id: "M-3", index: 3, label: "M3", description: "Guidelines PDF", proFee: 10000, status: "not_started", acceptanceCriteria: ["1-page guidelines delivered"], versions: [] },
    ],
    status: "active",
    createdAt: "2025-01-05T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-2",
  },
  {
    id: "QQ-0725",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    proId: "PRO-2099",
    proName: "Priya Nair",
    briefId: "BRF-0892",
    briefTitle: "Dashboard redesign",
    scope: "Redesign the internal analytics dashboard with new data viz and filters.",
    exclusions: ["No backend API changes", "No database work"],
    timeline: "5 weeks",
    totalProFee: 70000,
    revisions: 2,
    milestones: [
      { id: "M-1", index: 1, label: "M1", description: "Discovery + audit", proFee: 20000, status: "accepted", acceptanceCriteria: ["Audit report delivered"], versions: [{ id: "V-3", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-08T10:00:00Z", link: "https://notion.so/audit", changeNote: "Dashboard audit" }] },
      { id: "M-2", index: 2, label: "M2", description: "Hi-fi designs", proFee: 30000, status: "rejected", acceptanceCriteria: ["All 8 screens approved", "Design tokens documented"], versions: [{ id: "V-4", version: 1, status: "rejected", submitter: "pro", timestamp: "2025-01-15T10:00:00Z", link: "https://figma.com/dashboard-v1", changeNote: "Hi-fi v1 — missing filter states" }, { id: "V-5", version: 2, status: "in_review", submitter: "pro", timestamp: "2025-01-19T10:00:00Z", link: "https://figma.com/dashboard-v2", changeNote: "Hi-fi v2 — added filter states + empty states" }] },
      { id: "M-3", index: 3, label: "M3", description: "Handoff", proFee: 20000, status: "not_started", acceptanceCriteria: ["Design tokens + docs delivered"], versions: [] },
    ],
    status: "disputed",
    createdAt: "2025-01-03T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-2",
  },
  {
    id: "QQ-0730",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    briefId: "BRF-0901",
    briefTitle: "UX research for partner portal - 12 interviews",
    scope: "Conduct 12 moderated interviews with existing partners and synthesise into a journey map with top 10 prioritised insights.",
    exclusions: ["No quantitative survey", "No prototype creation"],
    timeline: "4 weeks",
    totalProFee: 60000,
    revisions: 1,
    milestones: [
      { id: "M-1", index: 1, label: "M1", description: "Script + recruitment", proFee: 20000, status: "accepted", acceptanceCriteria: ["Interview script approved", "12 participants confirmed"], versions: [{ id: "V-1", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-10T10:00:00Z", link: "https://notion.so/interview-script", changeNote: "Interview script + participant list" }] },
      { id: "M-2", index: 2, label: "M2", description: "Interviews + synthesis", proFee: 25000, status: "in_review", acceptanceCriteria: ["12 interviews completed", "Journey map delivered", "Top 10 insights documented"], versions: [{ id: "V-2", version: 1, status: "in_review", submitter: "pro", timestamp: "2025-01-18T14:00:00Z", link: "https://figma.com/journey-map", changeNote: "Journey map v1 + 12 interview summaries" }] },
      { id: "M-3", index: 3, label: "M3", description: "Final report", proFee: 15000, status: "not_started", acceptanceCriteria: ["Final report delivered", "Readout call scheduled"], versions: [] },
    ],
    status: "active",
    createdAt: "2025-01-05T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-2",
  },
  {
    id: "QQ-0735",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    briefId: "BRF-0920",
    briefTitle: "Private: Design ops audit (invite only)",
    scope: "Audit our design ops and propose improvements. 30/60/90 day plan.",
    exclusions: ["No implementation"],
    timeline: "2 weeks",
    totalProFee: 35000,
    revisions: 1,
    milestones: [
      { id: "M-1", index: 1, label: "M1", description: "Audit + plan", proFee: 35000, status: "accepted", acceptanceCriteria: ["Audit report delivered", "30/60/90 plan reviewed"], versions: [{ id: "V-1", version: 1, status: "accepted", submitter: "pro", timestamp: "2025-01-12T10:00:00Z", link: "https://notion.so/design-ops-audit", changeNote: "Design ops audit + 30/60/90 plan" }] },
    ],
    status: "disputed",
    createdAt: "2025-01-08T09:00:00Z",
    cancellationTerms: "Either party may request cancellation. Refund is governed by work-start status and Finance review. No automatic refund.",
    currentMilestoneId: "M-1",
  },
];

export const SEED_PAYMENTS: PaymentEvidence[] = [
  {
    id: "PAY-0892",
    contractId: "QQ-0892",
    milestoneId: "M-1",
    milestoneLabel: "M1",
    amountDue: 34200,
    utr: "UTR982341771",
    method: "NEFT",
    date: "2025-01-14T11:30:00Z",
    status: "under_admin_verification",
    targetReviewHours: 24,
    submittedAt: "2025-01-14T11:35:00Z",
  },
  {
    id: "PAY-0730",
    contractId: "QQ-0730",
    milestoneId: "M-1",
    milestoneLabel: "M1",
    amountDue: 20000,
    utr: "UTR771234500",
    method: "NEFT",
    date: "2025-01-09T10:00:00Z",
    status: "payment_confirmed",
    targetReviewHours: 24,
    submittedAt: "2025-01-09T10:05:00Z",
    resolvedAt: "2025-01-09T14:00:00Z",
  },
  {
    id: "PAY-0735",
    contractId: "QQ-0735",
    milestoneId: "M-1",
    milestoneLabel: "M1",
    amountDue: 35000,
    utr: "UTR771234501",
    method: "IMPS",
    date: "2025-01-07T10:00:00Z",
    status: "payment_confirmed",
    targetReviewHours: 24,
    submittedAt: "2025-01-07T10:05:00Z",
    resolvedAt: "2025-01-07T15:00:00Z",
  },
];

export const SEED_PAYOUTS: Payout[] = [
  {
    id: "PO-5001",
    contractId: "QQ-0700",
    proId: "PRO-2099",
    proName: "Priya Nair",
    milestoneLabel: "M2",
    proFee: 20000,
    commission: 0,
    netPayout: 20000,
    status: "queued",
    beneficiaryToken: "BNF-7781",
    queuedAt: "2025-01-08T10:00:00Z",
    slipAvailable: false,
  },
  {
    id: "PO-4990",
    contractId: "QQ-0650",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    milestoneLabel: "M3",
    proFee: 25000,
    commission: 0,
    statutoryWithholding: 2500,
    netPayout: 22500,
    status: "processed",
    reference: "NEFT-885511002",
    beneficiaryToken: "BNF-6612",
    queuedAt: "2024-12-28T10:00:00Z",
    processedAt: "2024-12-29T16:20:00Z",
    slipAvailable: true,
  },
  {
    id: "PO-5010",
    contractId: "QQ-0720",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    milestoneLabel: "M2",
    proFee: 18000,
    commission: 0,
    netPayout: 18000,
    status: "failed",
    beneficiaryToken: "BNF-6612",
    queuedAt: "2025-01-09T10:00:00Z",
    failureReason: "Beneficiary account number mismatch. Bank returned NEFT-771200441 as invalid.",
    slipAvailable: false,
  },
];

export const SEED_REFUNDS: Refund[] = [
  {
    id: "RF-3001",
    contractId: "QQ-0610",
    buyerId: "BUY-1042",
    buyerName: "Northstar Labs",
    amount: 15000,
    reason: "Mutual cancellation before work start",
    status: "requested",
    beneficiaryToken: "BNF-1042",
    createdAt: "2025-01-05T09:00:00Z",
  },
];

export const SEED_DISPUTES: Dispute[] = [
  {
    id: "DSP-7001",
    contractId: "QQ-0650",
    raisedBy: "buyer",
    raisedByName: "Northstar Labs",
    category: "quality_bugs",
    affectedMilestone: "M3",
    requestedResolution: "Partial refund - deliverable did not meet acceptance criterion 3.2",
    narrative: "The delivered brand guidelines missed the type scale section agreed in acceptance criteria.",
    evidence: ["Guideline_v2.pdf", "Acceptance_criteria.docx"],
    desiredOutcome: "₹7,000 refund and revised guidelines",
    status: "under_mediation",
    counterclaim: "Pro states the type scale was delivered in a separate file.",
    createdAt: "2025-01-02T09:00:00Z",
    slaOpenedAt: "2025-01-02T09:00:00Z",
    owner: "Deepa R (Risk T3)",
  },
  {
    id: "DSP-7002",
    contractId: "QQ-0725",
    raisedBy: "buyer",
    raisedByName: "Northstar Labs",
    category: "scope",
    affectedMilestone: "M2",
    requestedResolution: "Additional revision needed — filter states were not in the original scope but are required for the dashboard to function.",
    narrative: "The hi-fi designs (v1) are missing the filter active, empty, and loading states. These are essential for the dashboard to be usable. The Pro marked them as out of scope, but they were implied by 'All 8 screens approved' in the acceptance criteria.",
    evidence: ["Dashboard_v1_screenshot.png", "Acceptance_criteria_M2.pdf", "Scope_of_work.docx"],
    desiredOutcome: "Pro to add filter states in v2 at no additional cost",
    status: "opened",
    counterclaim: "Pro (Priya Nair) states the filter states were not explicitly listed in the acceptance criteria and would require additional effort. Offers to add them for ₹5,000 additional fee.",
    createdAt: "2025-01-16T14:00:00Z",
    slaOpenedAt: "2025-01-16T14:00:00Z",
    owner: "Deepa R (Risk T3)",
  },
  {
    id: "DSP-7003",
    contractId: "QQ-0735",
    raisedBy: "buyer",
    raisedByName: "Northstar Labs",
    category: "communication",
    affectedMilestone: "M1",
    requestedResolution: "Partial refund — the audit was delivered 5 days late and the 30/60/90 plan was incomplete (missing the design system governance section).",
    narrative: "The audit was supposed to be delivered in 2 weeks. It came 5 days late. The 30/60/90 plan is missing the design system governance section that was discussed in the kickoff call. The Pro has been unresponsive for 3 days after I flagged this.",
    evidence: ["Kickup_call_notes.pdf", "Audit_delivered_vs_scope.pdf", "Email_screenshots.png"],
    desiredOutcome: "₹10,000 partial refund and revised plan with governance section",
    status: "under_mediation",
    counterclaim: "Pro (Akhil Menon) states the delay was due to the Buyer not providing access to the design system until day 4. The governance section was not in the written acceptance criteria, only discussed verbally.",
    createdAt: "2025-01-15T09:00:00Z",
    slaOpenedAt: "2025-01-15T09:00:00Z",
    owner: "Deepa R (Risk T3)",
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "REV-1001",
    contractId: "QQ-0680",
    fromUserId: "BUY-1042",
    fromName: "Northstar Labs",
    toRole: "pro",
    rating: 5,
    comment: "Akhil delivered the ops console redesign ahead of schedule. The design tokens and handoff docs were exceptional. Would rehire.",
    visible: true,
    bothSubmitted: true,
    createdAt: "2025-01-17T10:00:00Z",
    images: [
      { id: "ri-1", color: "#7C3AED", label: "Ops console — dashboard screen" },
      { id: "ri-2", color: "#0891B2", label: "Design tokens delivered" },
      { id: "ri-3", color: "#CA8A04", label: "Handoff documentation" },
    ],
  },
  {
    id: "REV-1002",
    contractId: "QQ-0680",
    fromUserId: "PRO-2088",
    fromName: "Akhil Menon",
    toRole: "buyer",
    rating: 5,
    comment: "Clear brief, fast feedback, prompt milestone acceptance. Great client to work with.",
    visible: true,
    bothSubmitted: true,
    createdAt: "2025-01-17T12:00:00Z",
  },
];

export const SEED_TICKETS: SupportTicket[] = [
  {
    id: "TKT-9001",
    userId: "BUY-1042",
    userName: "Northstar Labs",
    category: "payment",
    subject: "UTR not matching in bank statement",
    description: "I submitted UTR982341771 but it is showing under verification for over 24h.",
    attachedContext: { contractId: "QQ-0892", paymentReference: "PAY-0892", status: "Under Admin Verification", latestEvent: "Evidence submitted 2025-01-14" },
    status: "assigned",
    owner: "Meera S (Support T1)",
    createdAt: "2025-01-15T08:00:00Z",
    messages: [
      { from: "user", text: "UTR not matching in bank statement", at: "2025-01-15T08:00:00Z" },
      { from: "admin", text: "Thanks, I am escalating to Finance for matcher review.", at: "2025-01-15T09:30:00Z" },
    ],
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  { id: "N-1", userId: "BUY-1042", type: "proposal_received", title: "New proposal on BRF-0892", body: "Akhil Menon submitted a proposal (₹85,000).", link: "buyer_brief_detail?briefId=BRF-0892", read: false, createdAt: "2025-01-12T10:01:00Z" },
  { id: "N-2", userId: "BUY-1042", type: "payment_submitted", title: "Payment evidence submitted", body: "PAY-0892 is under Admin verification. Target: 24h.", link: "buyer_payment?contractId=QQ-0892", read: false, createdAt: "2025-01-14T11:36:00Z" },
  { id: "N-3", userId: "PRO-2088", type: "contract_accepted", title: "Contract QQ-0892 accepted", body: "Northstar Labs accepted your offer. Funding pending.", link: "pro_contract?contractId=QQ-0892", read: false, createdAt: "2025-01-14T09:05:00Z" },
  { id: "N-4", userId: "PRO-2088", type: "sla_warning", title: "Do not begin work yet", body: "Payment verification pending for M1. Do not begin work until QuickQuid confirms funding.", link: "pro_contract?contractId=QQ-0892", read: false, createdAt: "2025-01-14T11:37:00Z" },
  { id: "N-5", userId: "FIN-F01", type: "payment_submitted", title: "Payment verification queued", body: "PAY-0892 awaiting matcher review.", link: "admin_payments", read: false, createdAt: "2025-01-14T11:36:00Z" },
  { id: "N-6", userId: "ADM-S01", type: "dispute_opened", title: "New dispute DSP-7001", body: "Quality/bugs dispute on QQ-0650.", link: "admin_disputes", read: false, createdAt: "2025-01-02T09:01:00Z" },
  { id: "N-7", userId: "PRO-2088", type: "payout_processed" as any, title: "Priority boost active", body: "Your priority payment (PB-5001) is confirmed. 'Design system audit' is now promoted in Buyer feed for 7 days.", link: "pro_gig_detail?gigId=GIG-3001", read: false, createdAt: new Date(Date.now() - 2 * 86400000).toISOString() },
  { id: "N-8", userId: "PRO-2099", type: "payment_submitted" as any, title: "Priority payment processing", body: "PB-5002 (₹2,500 for 14 days) is being processed via the integrated payment system.", link: "pro_gig_detail?gigId=GIG-3007", read: false, createdAt: new Date(Date.now() - 4 * 3600000).toISOString() },
  { id: "N-9", userId: "FIN-F01", type: "payment_submitted", title: "Priority boost verification queued", body: "PB-5002 (Priya Nair, ₹2,500) awaiting verification.", link: "admin_notes", read: false, createdAt: new Date(Date.now() - 4 * 3600000).toISOString() },
];

export const SEED_AUDIT: AuditEvent[] = [
  { id: "A-1", adminId: "FIN-F01", adminRole: "finance", action: "Payment confirmed", entity: "Payment", entityId: "PAY-0612", oldStatus: "Under Admin Verification", newStatus: "Payment Confirmed", timestamp: "2024-12-20T14:00:00Z", reason: "UTR matched bank evidence" },
  { id: "A-2", adminId: "FIN-F01", adminRole: "finance", action: "Payout authorized", entity: "Payout", entityId: "PO-4990", oldStatus: "Maker Confirmed", newStatus: "Checker Authorized", timestamp: "2024-12-28T15:00:00Z", reason: "Maker-checker threshold met" },
  { id: "A-3", adminId: "RSK-R01", adminRole: "risk", action: "Masked reveal", entity: "KYC", entityId: "KYC-2200", timestamp: "2024-12-22T10:00:00Z", reason: "Duplicate device signal investigation", maskedReveal: true },
  { id: "A-4", adminId: "RSK-R01", adminRole: "risk", action: "Account suspended", entity: "User", entityId: "PRO-1950", oldStatus: "Active", newStatus: "Suspended", timestamp: "2024-11-10T12:00:00Z", reason: "Repeat circumvention policy violation" },
];

export const SEED_KYC: KycSubmission[] = [
  {
    id: "KYC-2198",
    userId: "BUY-1042",
    userName: "Northstar Labs",
    role: "buyer",
    verificationType: "client",
    identityDocName: "authorized_signatory_pan.pdf",
    identityDocStatus: "uploaded",
    panMasked: "NS•••••PL",
    accountNumberMasked: "••••1042",
    ifscMasked: "HDFC••••",
    beneficiaryName: "Northstar Labs Private Limited",
    organizationName: "Northstar Labs Private Limited",
    organizationEvidenceName: "certificate_of_incorporation.pdf",
    status: "approved",
    submittedAt: "2024-09-20T09:00:00Z",
    resolvedAt: "2024-09-21T12:00:00Z",
  },
  {
    id: "KYC-2199",
    userId: "BUY-1050",
    userName: "Verdant Retail",
    role: "buyer",
    verificationType: "client",
    identityDocName: "authorized_signatory_pan.pdf",
    identityDocStatus: "uploaded",
    panMasked: "VR•••••TL",
    accountNumberMasked: "••••1050",
    ifscMasked: "ICIC••••",
    beneficiaryName: "Verdant Retail Private Limited",
    organizationName: "Verdant Retail Private Limited",
    organizationEvidenceName: "gst_registration.pdf",
    status: "approved",
    submittedAt: "2024-09-24T09:00:00Z",
    resolvedAt: "2024-09-25T13:00:00Z",
  },
  {
    id: "KYC-2201",
    userId: "PRO-2102",
    userName: "Sara Khan",
    role: "pro",
    verificationType: "professional",
    identityDocName: "aadhaar.jpg",
    identityDocStatus: "uploaded",
    panMasked: "AB•••••CD",
    accountNumberMasked: "••••3344",
    ifscMasked: "HDFC••••",
    beneficiaryName: "Sara Khan",
    skillVerifications: [
      { skill: "User Interviews", evidence: "Interview guide and anonymized synthesis sample", status: "under_review", submittedAt: "2025-01-16T09:00:00Z" },
      { skill: "Usability Testing", evidence: "Moderated test plan and findings sample", status: "under_review", submittedAt: "2025-01-16T09:00:00Z" },
    ],
    status: "under_review",
    submittedAt: "2025-01-16T09:00:00Z",
  },
  {
    id: "KYC-2202",
    userId: "PRO-2088",
    userName: "Akhil Menon",
    role: "pro",
    verificationType: "professional",
    identityDocName: "pan.jpg",
    identityDocStatus: "uploaded",
    panMasked: "AK•••••PM",
    accountNumberMasked: "••••4821",
    ifscMasked: "HDFC••••",
    beneficiaryName: "Akhil Menon",
    skillVerifications: [
      { skill: "Product Design", evidence: "Partner Portal and Ops Console case studies", status: "approved", submittedAt: "2024-09-30T09:00:00Z", reviewedAt: "2024-10-01T20:00:00Z", reviewedBy: "ADM-S01" },
      { skill: "UX Research", evidence: "Onboarding Flow Research case study", status: "approved", submittedAt: "2024-09-30T09:00:00Z", reviewedAt: "2024-10-01T20:00:00Z", reviewedBy: "ADM-S01" },
    ],
    status: "approved",
    submittedAt: "2024-10-01T09:00:00Z",
    resolvedAt: "2024-10-01T20:00:00Z",
  },
  {
    id: "KYC-2205",
    userId: "PRO-2099",
    userName: "Priya Nair",
    role: "pro",
    verificationType: "professional",
    identityDocName: "pan.pdf",
    identityDocStatus: "uploaded",
    panMasked: "PN•••••IR",
    accountNumberMasked: "••••2290",
    ifscMasked: "ICIC••••",
    beneficiaryName: "Priya Nair",
    skillVerifications: [
      { skill: "React", evidence: "SaaS Dashboard Kit", status: "approved", submittedAt: "2024-10-05T09:00:00Z", reviewedAt: "2024-10-06T14:00:00Z", reviewedBy: "ADM-S01" },
      { skill: "Next.js", evidence: "Next.js Landing Page case study", status: "approved", submittedAt: "2024-10-05T09:00:00Z", reviewedAt: "2024-10-06T14:00:00Z", reviewedBy: "ADM-S01" },
    ],
    status: "approved",
    submittedAt: "2024-10-05T09:00:00Z",
    resolvedAt: "2024-10-06T14:00:00Z",
  },
  {
    id: "KYC-2206",
    userId: "PRO-2101",
    userName: "Rahul Verma",
    role: "pro",
    verificationType: "professional",
    identityDocName: "passport.pdf",
    identityDocStatus: "uploaded",
    panMasked: "RV•••••MA",
    accountNumberMasked: "••••1180",
    ifscMasked: "SBIN••••",
    beneficiaryName: "Rahul Verma",
    skillVerifications: [
      { skill: "Brand Identity", evidence: "Fintech Brand System", status: "approved", submittedAt: "2024-10-09T09:00:00Z", reviewedAt: "2024-10-10T11:00:00Z", reviewedBy: "ADM-S01" },
    ],
    status: "approved",
    submittedAt: "2024-10-09T09:00:00Z",
    resolvedAt: "2024-10-10T11:00:00Z",
  },
  {
    id: "KYC-2203",
    userId: "PRO-2110",
    userName: "Test Pro (risk)",
    role: "pro",
    identityDocName: "id.png",
    identityDocStatus: "uploaded",
    panMasked: "TT•••••PP",
    accountNumberMasked: "••••9900",
    ifscMasked: "YESB••••",
    beneficiaryName: "Test Pro",
    status: "under_review",
    submittedAt: "2025-01-17T09:00:00Z",
    riskFlag: { signal: "device or network pattern matches a previously suspended account", confidence: 0.78, priorAccountStatus: "Suspended", hashedSignal: "h_8f2a91c4d7" },
  },
  {
    id: "KYC-2204",
    userId: "PRO-2111",
    userName: "Blurry Doc Pro",
    role: "pro",
    identityDocName: "id_blurry.jpg",
    identityDocStatus: "rejected",
    panMasked: "BD•••••PP",
    accountNumberMasked: "••••1234",
    ifscMasked: "ICIC••••",
    beneficiaryName: "Blurry Doc Pro",
    status: "rejected",
    submittedAt: "2025-01-10T09:00:00Z",
    resolvedAt: "2025-01-11T09:00:00Z",
    rejectionReason: "Image is too blurry. Upload a clearer document.",
  },
];

export const SEED_GIGS: GigDraft[] = [
  {
    id: "GIG-3001",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    title: "Design system audit & token delivery",
    category: "Product Design",
    subcategory: "Design Systems",
    tags: ["design systems", "tokens", "figma"],
    shortDescription: "Audit your existing product UI and deliver a documented design token set.",
    detailedDescription: "I will audit your product UI across 10 key screens, identify inconsistencies, and deliver a documented design token set in Figma + JSON. QuickQuid deducts 0% commission from your fee.",
    includedItems: ["Audit report", "Token JSON", "Figma library"],
    exclusions: ["No implementation in code"],
    deliverableFormat: "Figma link + JSON",
    revisions: 2,
    deliveryTimeline: "10 days",
    buyerRequirements: ["Provide Figma access", "Share 3 priority screens"],
    evidence: ["Partner Portal Case Study"],
    coverImageColor: "#7C3AED",
    coverImageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/62c63cd0aad8.png",
    packageName: "Standard",
    proFee: 25000,
    availability: true,
    maxConcurrentOrders: 2,
    status: "approved_live",
    createdAt: "2025-01-09T09:00:00Z",
    views: 142,
    requests: 6,
    rating: 4.9,
  },
  {
    id: "GIG-3002",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    title: "Partner onboarding flow - design only",
    category: "Product Design",
    subcategory: "Onboarding",
    tags: ["onboarding", "saas", "ux"],
    shortDescription: "End-to-end partner onboarding flow design with usability testing.",
    detailedDescription: "Discovery, wireframes, hi-fi, prototype, and 5-partner usability test.",
    includedItems: ["Wireframes", "Hi-fi screens", "Prototype", "Usability report"],
    exclusions: ["No development", "No SEO"],
    deliverableFormat: "Figma link",
    revisions: 2,
    deliveryTimeline: "4 weeks",
    buyerRequirements: ["Stakeholder availability for discovery"],
    evidence: [],
    coverImageColor: "#0891B2",
    packageName: "Standard",
    proFee: 60000,
    availability: true,
    maxConcurrentOrders: 1,
    status: "under_review",
    createdAt: "2025-01-18T09:00:00Z",
    views: 22,
    requests: 1,
  },
  {
    id: "GIG-3003",
    proId: "PRO-2099",
    proName: "Priya Nair",
    title: "Next.js landing page",
    category: "Frontend Engineering",
    subcategory: "Landing Pages",
    tags: ["nextjs", "react", "tailwind"],
    shortDescription: "Production-grade, accessible Next.js landing page.",
    detailedDescription: "A responsive, accessible landing page in Next.js + Tailwind. Lighthouse 95+.",
    includedItems: ["Source code", "Deployment guide"],
    exclusions: ["No backend", "No CMS integration"],
    deliverableFormat: "GitHub repo",
    revisions: 1,
    deliveryTimeline: "7 days",
    buyerRequirements: ["Provide brand assets"],
    evidence: ["SaaS Dashboard Kit"],
    coverImageColor: "#0EA5E9",
    packageName: "Basic",
    proFee: 30000,
    availability: true,
    maxConcurrentOrders: 2,
    status: "changes_requested",
    createdAt: "2025-01-19T09:00:00Z",
    views: 18,
    requests: 0,
    moderationReason: "Missing deliverable: deployment guide unclear",
  },
  {
    id: "GIG-3004",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    title: "Logo + brand mark in 3 days",
    category: "Brand & Identity",
    subcategory: "Logo Design",
    tags: ["logo", "branding", "identity"],
    shortDescription: "Fast turnaround logo design with 3 concepts and unlimited revisions until final.",
    detailedDescription: "You get 3 logo concepts, unlimited revisions on the chosen direction, and final files in SVG, PNG, and PDF. QuickQuid deducts 0% commission from your fee.",
    includedItems: ["3 logo concepts", "Unlimited revisions", "Final files (SVG/PNG/PDF)", "Black & white versions"],
    exclusions: ["No full brand guidelines", "No stationery design"],
    deliverableFormat: "SVG + PNG + PDF",
    revisions: 99,
    deliveryTimeline: "3 days",
    buyerRequirements: ["Provide brand name", "Share 2-3 reference logos"],
    evidence: ["Fintech Brand System"],
    coverImageColor: "#DB2777",
    packageName: "Basic",
    proFee: 15000,
    availability: true,
    maxConcurrentOrders: 3,
    status: "submitted",
    createdAt: "2025-01-19T09:00:00Z",
    views: 0,
    requests: 0,
  },
  {
    id: "GIG-3005",
    proId: "PRO-2099",
    proName: "Priya Nair",
    title: "React component library (20 components)",
    category: "Frontend Engineering",
    subcategory: "Component Libraries",
    tags: ["react", "components", "typescript", "tailwind"],
    shortDescription: "Production-ready React component library with 20 accessible components and Storybook.",
    detailedDescription: "20 accessible React components built with TypeScript and Tailwind. Includes Storybook documentation, unit tests, and an npm package. QuickQuid deducts 0% commission.",
    includedItems: ["20 React components", "Storybook setup", "Unit tests", "npm package", "Documentation"],
    exclusions: ["No custom design system", "No backend integration"],
    deliverableFormat: "GitHub repo + npm",
    revisions: 1,
    deliveryTimeline: "10 days",
    buyerRequirements: ["Provide design tokens if any"],
    evidence: ["SaaS Dashboard Kit"],
    coverImageColor: "#0EA5E9",
    packageName: "Standard",
    proFee: 45000,
    availability: true,
    maxConcurrentOrders: 1,
    status: "rejected",
    createdAt: "2025-01-15T09:00:00Z",
    views: 5,
    requests: 0,
    moderationReason: "Contact/payment information detected in description. Remove UPI ID before resubmitting.",
  },
  {
    id: "GIG-3006",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    title: "Usability testing for SaaS (5 participants)",
    category: "UX Research",
    subcategory: "Usability Testing",
    tags: ["usability", "research", "testing"],
    shortDescription: "Moderated usability testing with 5 participants, synthesis, and prioritised findings.",
    detailedDescription: "Recruit 5 participants matching your persona, run 45-min moderated sessions, synthesise into a journey map with top 10 prioritised findings.",
    includedItems: ["Participant recruitment", "5 moderated sessions", "Journey map", "Prioritised findings report"],
    exclusions: ["No quantitative survey", "No prototype creation"],
    deliverableFormat: "Notion doc + video clips",
    revisions: 1,
    deliveryTimeline: "2 weeks",
    buyerRequirements: ["Provide prototype access", "Confirm persona criteria"],
    evidence: ["Onboarding Flow Research"],
    coverImageColor: "#CA8A04",
    packageName: "Standard",
    proFee: 35000,
    availability: false,
    maxConcurrentOrders: 2,
    status: "paused",
    createdAt: "2025-01-10T09:00:00Z",
    views: 89,
    requests: 3,
    rating: 4.8,
  },
  {
    id: "GIG-3007",
    proId: "PRO-2099",
    proName: "Priya Nair",
    title: "Production Next.js SaaS dashboard",
    category: "Frontend Engineering",
    subcategory: "SaaS Dashboards",
    tags: ["nextjs", "dashboard", "tailwind", "saas"],
    shortDescription: "Complete responsive SaaS dashboard with charts, tables, and dark mode.",
    detailedDescription: "A production-grade SaaS dashboard built with Next.js 16, Tailwind CSS 4, and shadcn/ui. Includes 10+ chart types, data tables, filters, and full dark mode support. QuickQuid deducts 0% commission.",
    includedItems: ["Dashboard layout", "10+ chart types", "Data tables with filters", "Dark mode", "Responsive (390/768/1440)"],
    exclusions: ["No backend API", "No database setup"],
    deliverableFormat: "GitHub repo + deployment guide",
    revisions: 2,
    deliveryTimeline: "12 days",
    buyerRequirements: ["Provide brand colors", "Share data schema"],
    evidence: ["SaaS Dashboard Kit"],
    coverImageColor: "#0EA5E9",
    coverImageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9628ecf06ad9.jpg",
    packageName: "Premium",
    proFee: 75000,
    availability: true,
    maxConcurrentOrders: 1,
    status: "approved_live",
    createdAt: "2025-01-05T09:00:00Z",
    views: 312,
    requests: 14,
    rating: 4.9,
  },
  {
    id: "GIG-3008",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    title: "Complete brand identity system",
    category: "Brand & Identity",
    subcategory: "Brand Guidelines",
    tags: ["branding", "logo", "guidelines", "identity"],
    shortDescription: "Logo, color palette, typography, and full brand guidelines document.",
    detailedDescription: "A complete brand identity system: 3 logo concepts, color palette with hex codes, typography pairing, and a 20-page brand guidelines PDF. QuickQuid deducts 0% commission.",
    includedItems: ["3 logo concepts", "Color palette", "Typography system", "20-page guidelines PDF", "Social media kit"],
    exclusions: ["No website design", "No packaging design"],
    deliverableFormat: "AI + PDF + PNG",
    revisions: 3,
    deliveryTimeline: "8 days",
    buyerRequirements: ["Complete brand brief", "2-3 reference brands"],
    evidence: ["Fintech Brand System"],
    coverImageColor: "#DB2777",
    coverImageUrl: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ab448629fbb2.jpg",
    packageName: "Standard",
    proFee: 50000,
    availability: true,
    maxConcurrentOrders: 2,
    status: "approved_live",
    createdAt: "2025-01-03T09:00:00Z",
    views: 198,
    requests: 9,
    rating: 4.8,
  },
  {
    id: "GIG-3009",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    title: "UX audit + usability report",
    category: "UX Research",
    subcategory: "UX Audits",
    tags: ["ux audit", "usability", "research", "report"],
    shortDescription: "Expert UX audit of your product with prioritised, actionable findings.",
    detailedDescription: "A thorough UX audit of your product across 15 heuristics, with a prioritised report of findings, severity ratings, and actionable recommendations. QuickQuid deducts 0% commission.",
    includedItems: ["15-heuristic audit", "Prioritised findings report", "Severity ratings", "Actionable recommendations", "60-min walkthrough call"],
    exclusions: ["No redesign work", "No implementation"],
    deliverableFormat: "Notion doc + Loom video",
    revisions: 1,
    deliveryTimeline: "5 days",
    buyerRequirements: ["Provide product URL", "Share user personas if available"],
    evidence: ["Onboarding Flow Research", "Partner Portal Case Study"],
    coverImageColor: "#CA8A04",
    packageName: "Standard",
    proFee: 35000,
    availability: true,
    maxConcurrentOrders: 3,
    status: "approved_live",
    createdAt: "2025-01-07T09:00:00Z",
    views: 156,
    requests: 7,
    rating: 4.7,
  },
  {
    id: "GIG-3010",
    proId: "PRO-2099",
    proName: "Priya Nair",
    title: "Landing page in 48 hours",
    category: "Frontend Engineering",
    subcategory: "Landing Pages",
    tags: ["landing", "nextjs", "tailwind", "fast"],
    shortDescription: "High-converting, responsive landing page delivered in 48 hours. Lighthouse 95+.",
    detailedDescription: "A production-grade landing page built with Next.js and Tailwind CSS. Includes hero, features, pricing, testimonials, FAQ, and CTA sections. Fully responsive and accessible. QuickQuid deducts 0% commission.",
    includedItems: ["Landing page (7 sections)", "Responsive (390/768/1440)", "Lighthouse 95+", "Contact form", "SEO meta tags"],
    exclusions: ["No backend integration", "No CMS"],
    deliverableFormat: "GitHub repo + Vercel deploy",
    revisions: 1,
    deliveryTimeline: "2 days",
    buyerRequirements: ["Provide brand assets", "Share copy/content"],
    evidence: ["SaaS Dashboard Kit"],
    coverImageColor: "#10B981",
    packageName: "Basic",
    proFee: 20000,
    availability: true,
    maxConcurrentOrders: 3,
    status: "approved_live",
    createdAt: "2025-01-08T09:00:00Z",
    views: 234,
    requests: 11,
    rating: 4.9,
  },
  {
    id: "GIG-3011",
    proId: "PRO-2102",
    proName: "Sara Khan",
    title: "User research interviews (10 participants)",
    category: "UX Research",
    subcategory: "User Interviews",
    tags: ["research", "interviews", "usability", "ux"],
    shortDescription: "10 moderated user interviews with transcription, synthesis, and journey mapping.",
    detailedDescription: "Recruit 10 participants matching your persona, run 45-min moderated interviews, transcribe, synthesise into a journey map with top 10 insights. QuickQuid deducts 0% commission.",
    includedItems: ["Participant recruitment (10)", "45-min moderated sessions", "Transcriptions", "Journey map", "Top 10 insights report"],
    exclusions: ["No quantitative survey", "No prototype design"],
    deliverableFormat: "Notion doc + video clips",
    revisions: 1,
    deliveryTimeline: "10 days",
    buyerRequirements: ["Provide persona criteria", "Share research goals"],
    evidence: [],
    coverImageColor: "#8B5CF6",
    packageName: "Standard",
    proFee: 40000,
    availability: true,
    maxConcurrentOrders: 2,
    status: "approved_live",
    createdAt: "2025-01-06T09:00:00Z",
    views: 127,
    requests: 5,
    rating: 4.6,
  },
];

export const SEED_OFFLINE_INSTRUMENTS: OfflineInstrument[] = [
  {
    id: "OI-4001",
    contractRef: "QQ-0620",
    instrumentType: "Cheque",
    bank: "HDFC Bank",
    instrumentNumber: "CHQ-551200",
    amount: 50000,
    receivedDate: "2025-01-03",
    expectedSettlement: "2025-01-06",
    owner: "Arjun K (Finance T2)",
    status: "dishonoured",
  },
];

export const SEED_TRUST_CASES: TrustSafetyCase[] = [
  {
    id: "TS-6001",
    complainant: "Northstar Labs",
    affectedEntity: "Pro profile PRO-1950",
    allegation: "Pro attempted to take payment off-platform via shared UPI link in messages.",
    evidence: ["Message screenshot", "Circumvention log"],
    urgency: "high",
    owner: "Deepa R (Risk T3)",
    status: "investigating",
    actionHistory: [
      { action: "Case opened", at: "2025-01-04T10:00:00Z", by: "System" },
      { action: "Assigned to Risk T3", at: "2025-01-04T10:05:00Z", by: "Meera S (Support T1)" },
    ],
    createdAt: "2025-01-04T10:00:00Z",
  },
];

export const ADMIN_NOTES = [
  "v0.1 prototype: payments flow through the integrated payment system. Payouts are processed via the provider's API.",
  "Buyer fee is 0%. No platform commission is taken from the Pro fee.",
  "Pro commission is 0%. Pro fee and Buyer fee are always separate line items.",
  "Maximum 4 milestones per contract in v0.1.",
  "Taxes shown as 'Calculated by Finance if applicable' - never hardcode TDS/GST/TCS rates.",
  "Sensitive data (PAN, bank account, IFSC) is masked by default. Reveal requires reason + audit event.",
  "Role switcher (bottom-left) is restricted to prototype mode for demo/QA only.",
  "All money-movement actions go through maker-checker for Finance and produce audit events.",
];

export const SEED_PRIORITY_BOOSTS: PriorityBoost[] = [
  {
    id: "PB-5001",
    gigId: "GIG-3001",
    proId: "PRO-2088",
    proName: "Akhil Menon",
    priorityFee: 1500,
    duration: 7,
    paymentReference: "UTR991234567",
    paymentMethod: "NEFT",
    paymentStatus: "active",
    priorityStart: new Date(Date.now() - 2 * 86400000).toISOString(),
    priorityEnd: new Date(Date.now() + 5 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    resolvedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    makerId: "FIN-F01",
    analytics: { views: 89, clicks: 23, requests: 4 },
  },
  {
    id: "PB-5002",
    gigId: "GIG-3007",
    proId: "PRO-2099",
    proName: "Priya Nair",
    priorityFee: 2500,
    duration: 14,
    paymentReference: "UTR991234568",
    paymentMethod: "IMPS",
    paymentStatus: "under_admin_verification",
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    analytics: { views: 0, clicks: 0, requests: 0 },
  },
  {
    id: "PB-5003",
    gigId: "GIG-3008",
    proId: "PRO-2101",
    proName: "Rahul Verma",
    priorityFee: 800,
    duration: 3,
    paymentStatus: "draft",
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    analytics: { views: 0, clicks: 0, requests: 0 },
  },
  {
    id: "PB-5004",
    gigId: "GIG-3010",
    proId: "PRO-2099",
    proName: "Priya Nair",
    priorityFee: 1500,
    duration: 7,
    paymentStatus: "expired",
    priorityStart: new Date(Date.now() - 10 * 86400000).toISOString(),
    priorityEnd: new Date(Date.now() - 3 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    resolvedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    makerId: "FIN-F01",
    analytics: { views: 145, clicks: 34, requests: 6 },
  },
];
